# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresstest', '0003_address_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address_info',
            name='data',
        ),
    ]
